#! /bin/sh
#  -*- Mode: Shell-script -*- 
# ----------------------------------------------------------------------
# configure --- maintainer's bootstrap configure script
#
# Author:            Bruce Korb <bkorb@gnu.org>
# Maintainer:        Bruce Korb <bkorb@gnu.org>
# Created:           Fri Jul 30 10:57:13 1999
# Last Modified:     Mon Aug  9 10:15:42 1999				      
#            by:     Bruce Korb <bkorb@gnu.org>			      
# ----------------------------------------------------------------------
# @(#) $Id: mkconfig.sh,v 2.14 2000/09/11 00:36:43 bkorb Exp $
# ----------------------------------------------------------------------

if [ "$1" = "-CVS" ]
then update_cvs=false
else update_cvs=true ; fi

exec 5> temp.config

GENLIST="agen5/autogen.1
	 agen5/directive.h
	 agen5/defParse.c
	 agen5/defParse.h
	 agen5/expr.h
	 agen5/expr.ini
	 agen5/functions.h
	 agen5/opts.c
	 agen5/opts.h
	 agen5/autogen.menu
	 agen5/autogen.texi
	 autoopts/genshell.c
	 autoopts/genshell.h"

for f in ${GENLIST}
do
  [ -f $f ] || {
    echo "Error:  cannot generate configure without $f" >&2
    exit 1
  }
done
touch_list="`egrep '## stamp-.*GEN-RULE' agen5/Makefile.am | \
             sed 's@.*## *\(.*\) GEN-RULE@agen5/\1@' `"

if ${update_cvs} && [ -d CVS ]
then
  rm -f ./configure
  cvs update configure > /dev/null 2>&1
fi

[ -f doc/autogen.texi ] || {
  echo '@setfilename completely.bogus' > doc/autogen.texi
  touch -t 200001010000 doc/autogen.texi
}

#  Make sure the new file removes the current collection of files
#
cat <<'_EOF_' >&5
#! /bin/sh
#
#  DO NOT EDIT THIS FILE
#
#  It is generated by :mkconfig.  Make necessary changes there.
#		      
# ----------------------------------------------------------------------

SVDIR=`pwd`
cd `echo $0 | sed 's;/[^/]*$;;'`
SRCDIR=`pwd`

if [ ! -f ./configure.in ]
then
  echo cannot locate top source directory for AutoGen
  exit 1
fi

#  Touch the stamp-* files so bootstrap.dir won't try to build them
#
_EOF_

cat >&5 <<_EOF_
touch -t 200001010000 `echo ${touch_list}`

_EOF_

for f in ./configure ${GENLIST}
do echo $f ; done | \
columns -I10 --first='for f in ' --line=' \' >&5

cat <<'_EOF_' >&5
do
  if [ -f $f ]
  then
    rm -f $f || {
      echo cannot remove $f
      exit 1
    }
  fi
done

_EOF_

#  Add the text to create the needed generated files
#
shar -T -w -D -Q ${GENLIST} | \
  sed -e '1,/== agen5\/autogen.1 ==/d' \
      -e '/DO NOT EDIT THIS FILE/,/and the template file/d' \
      -e 's/.shar_touch -am [0-9]* /touch -t 200001010000 /' \
      -e '/lock directory/,$d' \
  >&5

#  Finally, add the code that generates the files generated
#  by standard tools (yacc/byacc/bison).
#
cat <<'_EOF_' >&5

sh config/bootstrap $@ || exit 1
cd $SVDIR
sh ${SRCDIR}/configure $@
_EOF_
echo "# configure ends here" >&5

exec 5>&-

if cmp configure temp.config
then
  echo configure is unchanged
  rm -f temp.config
else
  if $update_cvs
  then
    cvs edit configure
    mv -f temp.config configure
    cvs commit -m'CVS-ed configure script update' configure
  else
    (
      echo configure would change:
      echo diff -c configure temp.config
      diff -c configure temp.config
    ) | ${PAGER-more}
  fi
fi

# :mkconfig ends here
