#! /bin/sh
set -x

# Time-stamp:        "2007-04-28 13:12:17 bkorb"
# Last Committed:    $Date: 2007/06/23 20:19:39 $

egrep '#undef +AUTOOPTS_ENABLED' ${top_builddir}/config.h >/dev/null && \
 exit 0

srcdir=`dirname $0`
srcdir=`cd ${srcdir} ; pwd`
rm -f ${destdir}/options.h
exec 3> ${destdir}/options.h
sed '/^#include <sys/q' ${srcdir}/autoopts/options.h >&3

if egrep 'define +HAVE_STDINT_H' ${top_builddir}/config.h >/dev/null
then echo '#include <stdint.h>' >&3
else echo '#include <inttypes.h>' >&3 ; fi

if egrep 'define +HAVE_LIMITS_H' ${top_builddir}/config.h >/dev/null
then echo '#include <limits.h>' >&3
else echo '#include <sys/limits>' >&3 ; fi

if egrep 'define +HAVE_U_INT' ${top_builddir}/config.h >/dev/null
then :
else echo 'typedef unsigned int u_int;' >&3 ; fi

if egrep 'define +HAVE_SYSEXITS_H' ${top_builddir}/config.h >/dev/null
then echo '#include <sysexits.h>' >&3 ; fi

egrep 'define +NO_OPTIONAL_OPT_ARGS' ${top_builddir}/config.h >&3

sed '1,/endif.*HAVE_SYSEXITS_H/d' ${srcdir}/autoopts/options.h >&3

exec 3>&-
