
# cright-update Makefile

           TOP = ..
           SRC = $(EXE).c
           OBJ = $(SRC:.c=.o)
           EXE = cright-update
        TARGET = $(EXE)
        OPTDEF = opts.def
      CMAPFILE = cright.map
        FSMDEF = collapse

        CFLAGS = -g -O0

include $(TOP)/MakeRules
