
##  This file is part of cright-update.
##  cright-update Copyright (C) 2002-2015 by Bruce Korb - all rights reserved
##
## cright-update is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by the
## Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## cright-update is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
## See the GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License along
## with this program.  If not, see <http://www.gnu.org/licenses/>.

# cright-update Makefile

           TOP = ..
           SRC = $(EXE).c
           OBJ = $(SRC:.c=.o)
           EXE = cright-update
        TARGET = $(EXE)
        OPTDEF = opts.def
      CMAPFILE = cright.map
        FSMDEF = collapse

        CFLAGS = -g2 -O0

include $(TOP)/MakeRules
